modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="jram"
version="1.0.0"
displayName="Just Another Ruby Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Home, MCreator"

[[dependencies.jram]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



