    - name: Create a Release
      uses: actions/create-release@v1
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: 
        # The name of the release. For example, `Release v1.0.1`
        release_name:  Release test
        prerelease: true
