# This workflow will build a Java project with Gradle	
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle	

name: Java CI with Gradle	

on:	
  push:	
    branches: [ master ]	
  pull_request:	
    branches: [ master ]	

jobs:	
  build:	

    runs-on: ubuntu-latest	

    steps:	
    - uses: travisj/build-number-action@v1
      id: my-project-build-number
    - uses: actions/checkout@v2	
      

        
    - name: Set up JDK 1.8	
      uses: actions/setup-java@v1	
      with:	
        java-version: 1.8	
    
    - name: Echo file name
      run: echo  build/libs/JARM-${{ steps.my-project-build-number.outputs.build-number }}.jar
      env:
        BUILD_NUMBER: ${{ steps.my-project-build-number.outputs.build-number }}
          
    - name: Grant execute permission for gradlew	
      run: chmod +x gradlew	
      
    - name: Build with Gradle	
      run: ./gradlew build
      
    - name: rename file
      env:
        TIME: "${{ steps.current-time.outputs.formattedTime }}"
      run: mv build/libs/modid-1.0.jar build/libs/JARM-${{ steps.my-project-build-number.outputs.build-number }}.jar
      
    - name: Upload a Build Artifact	
      uses: actions/upload-artifact@v2.0.1
      env:
        TIME: ${{ steps.current-time.outputs.time }}
      with:	
        # Artifact name	
        name: JARM-${{ steps.my-project-build-number.outputs.build-number }}.jar
        # A file, directory or wildcard pattern that describes what to upload	
        path: build/libs/JARM-${{ steps.my-project-build-number.outputs.build-number }}.jar
        
    - name: Upload to curseforge
      env:
        TIME: ${{ steps.current-time.outputs.time }}
      uses: itsmeow/curseforge-upload@master
      with:
        token: ${{ secrets.CF_API_KEY }}
        project_id: 385265
        game_endpoint: minecraft
        file_path: build/libs/JARM-${{ steps.my-project-build-number.outputs.build-number }}.jar
        changelog: updated mod, changelog on github
        display_name: JARM-0.0.${{ steps.my-project-build-number.outputs.build-number }}
        game_versions: 1.15.2,Java 8,Forge
        release_type: alpha
        
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        # Note-worthy description of changes in release
        body: still need to make one :\\
        # Gives the release a custom name. Defaults to tag name
        name: ${{ steps.my-project-build-number.outputs.build-number }}
        # Identify the release as a prerelease. Defaults to false
        prerelease: true
        # Newline-delimited list of path globs for asset files to upload
        files: build/libs/JARM-${{ steps.my-project-build-number.outputs.build-number }}.jar
