# This workflow will build a Java project with Gradle	
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle	

name: Java CI with Gradle	

on:	
  push:	
    branches: [ master ]	
  pull_request:	
    branches: [ master ]	

jobs:	
  build:	

    runs-on: ubuntu-latest	

    steps:	
    - uses: actions/checkout@v2	
    - name: Set up JDK 1.8	
      uses: actions/setup-java@v1	
      with:	
        java-version: 1.8	
    - name: Get Current Time
      uses: 1466587594/get-current-time@v1.0.0
      with:
        # Time format to use using [MomemtJS format syntax](https://momentjs.com/docs/#/displaying/format/)
        format: MM-DD

    - name: Create a Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TIME: "${{ steps.current-time.outputs.time }}"
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: ${{ steps.current-time.outputs.formattedTime }}
        # The name of the release. For example, `Release v1.0.1`
        release_name:  Release test
        prerelease: true
    - name: Grant execute permission for gradlew	
      run: chmod +x gradlew	
    - name: Build with Gradle	
      run: ./gradlew build
    - name: rename file
      env:
        TIME: "${{ steps.current-time.outputs.formattedTime }}"
      run: mv build/libs/modid-1.0.jar "build/libs/JARM-"+"${{ steps.current-time.outputs.formattedTime }}"+".jar"
    - name: Upload a Build Artifact	
      uses: actions/upload-artifact@v2.0.1
      env:
        TIME: ${{ steps.current-time.outputs.time }}
      with:	
        # Artifact name	
        name: JARM.jar
        # A file, directory or wildcard pattern that describes what to upload	
        path: build/libs/JARM-"+"${{ steps.current-time.outputs.formattedTime }}"+".jar
    - name: Upload to curseforge
      env:
        TIME: ${{ steps.current-time.outputs.time }}
      uses: itsmeow/curseforge-upload@master
      with:
        token: ${{ secrets.CF_API_KEY }}
        project_id: 385265
        game_endpoint: minecraft
        file_path: build/libs/JARM-"+"${{ steps.current-time.outputs.formattedTime }}"+".jar
        changelog: updated mod, changelog on github
        display_name: JARM
        game_versions: 1.15.2,Java 8,Forge
        release_type: alpha
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The URL for uploading assets to the release
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        # The path to the asset you want to upload
        asset_path: build/libs/
        # The name of the asset you want to upload
        asset_name: ${{ steps.current-time.outputs.formattedTime }}+".jar"
        # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
        asset_content_type: application/zip
